stages:
  - sonar-check

sonarqube-check:
  stage: sonar-check
  image: sonarsource/sonar-scanner-cli:latest
  tags:
    - sonarqube
  before_script:
    - chmod +x ci/scan-and-update.sh
  script:
    - ./ci/scan-and-update.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
