stages:
  - build-sonar

build-sonar:
  stage: build-sonar
  tags:
    - sonarqube
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-21-openjdk-amd64"
    PATH: "/opt/sonar-scanner/bin:/usr/lib/jvm/java-21-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    SONAR_SCANNER_OPTS: "-Djava.home=/usr/lib/jvm/java-21-openjdk-amd64"

  script:
    - echo "✅ Java 확인"
    - java -version
    - echo "✅ SonarScanner 버전"
    - sonar-scanner -v
    - echo "✅ sonar-project.properties 내용 확인"
    - cat sonar-project.properties
    - echo "✅ sonar-scanner 실행"
    - sonar-scanner -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_TOKEN" -X

  allow_failure: true
  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'
