sonar.projectKey=luna_luna-devops-frontend_02c67b54-1c46-47db-8ad7-c7ec854e43a2
sonar.projectName=luna-devops-frontend
sonar.sources=src
#sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
